### ISSUE TITLE
NetStandard 2.0 support

### ISSUE THREAD

**Issue by kachalkov** [barakbbn/WpfMartHelp#1]
hi guys,

great library, any chance to get it compiled targeting Netstandard 2.0

**Comment by barakbbn** [comment]
which target Frameworks you expect to support? (.NET Framework v?,    .Net Core v?     .Net 5? 6?) 
Since if only targeting  Netstandard 2.0, some of the WPF Classes/Interfaces used by this package are not supported

**Comment by kachalkov** [comment]
Netcore 3.1

**Comment by barakbbn** [comment]
Support targeting to .NET Core 3 , .NET 4.8 , .NET 4.5.2
